from google import genai
import os
import uuid
import logging

logger = logging.getLogger(__name__)


class GeminiImageService:
    def __init__(self):
        """Initialize the Gemini image generation service"""
        self.api_key = os.environ.get("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY environment variable is required")
        
        self.client = genai.Client(api_key=self.api_key)
        self.output_dir = "generated_images"
        
        # Create output directory if it doesn't exist
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_image(self, prompt: str) -> tuple[str, str]:
        """
        Generate an image using Gemini's imagen model
        
        Args:
            prompt: Text description of the image to generate
            
        Returns:
            tuple: (filename, image_url)
        """
        try:
            logger.info(f"Generating image with Gemini for prompt: {prompt[:50]}...")
            
            result = self.client.models.generate_images(
                model="models/imagen-4.0-generate-001",
                prompt=prompt,
                config=dict(
                    number_of_images=1,
                    output_mime_type="image/jpeg",
                    aspect_ratio="1:1",
                    image_size="1K",
                ),
            )

            if not result.generated_images:
                raise Exception("No images generated by Gemini API")

            if len(result.generated_images) != 1:
                logger.warning("Number of images generated does not match the requested number")

            # Generate unique filename
            filename = f"gemini_{uuid.uuid4().hex}.jpg"
            filepath = os.path.join(self.output_dir, filename)
            
            # Save the generated image
            generated_image = result.generated_images[0]
            generated_image.image.save(filepath)
            
            # Return filename and URL
            image_url = f"/static/generated_images/{filename}"
            
            logger.info(f"Image generated successfully: {filename}")
            return filename, image_url
            
        except Exception as e:
            logger.error(f"Error generating image with Gemini: {str(e)}")
            raise Exception(f"Failed to generate image: {str(e)}")


# Create a singleton instance
gemini_service = GeminiImageService()